// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20230605173707_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Honolulu",
                            Country = "United States",
                            Description = "Lovely vacation destination with great weather. No spiders at all!",
                            Rating = 9,
                            UserName = "Mr_ReviewGuy"
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "San Diego",
                            Country = "United States",
                            Description = "Sunny San Diego offers a perfect blend of beach bliss and urban spiders",
                            Rating = 7,
                            UserName = "Marcus"
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Chicago",
                            Country = "United States",
                            Description = "Tons of spiders, I loved it",
                            Rating = 10,
                            UserName = "Jumping_Spider"
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Tokyo",
                            Country = "Japan",
                            Description = "Basically the future, they have robot spiders",
                            Rating = 8,
                            UserName = "Marcus"
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Honolulu",
                            Country = "United States",
                            Description = "My stay was decent, this place could use some more spiders. I am going to steal the Declaration of Independence.",
                            Rating = 6,
                            UserName = "Nic_Cage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
