// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20230606180611_AddNewSeedData")]
    partial class AddNewSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Address = "123 Beach st",
                            City = "Honolulu",
                            Country = "United States",
                            Date = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lovely vacation destination with great weather. No spiders at all!",
                            Destination = "Waikiki Beach",
                            Rating = 9,
                            UserName = "Mr_ReviewGuy"
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "San Diego",
                            Country = "United States",
                            Date = new DateTime(2006, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sunny San Diego offers a perfect blend of beach bliss and urban spiders",
                            Destination = "Coronado",
                            Rating = 7,
                            UserName = "Marcus"
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Chicago",
                            Country = "United States",
                            Date = new DateTime(2011, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tons of spiders, I loved it",
                            Destination = "Lou Malnati's Pizzaria",
                            Rating = 10,
                            UserName = "Jumping_Spider"
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Tokyo",
                            Country = "Japan",
                            Date = new DateTime(2009, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basically the future, they have robot spiders",
                            Destination = "マクドナルド",
                            Rating = 8,
                            UserName = "Marcus"
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Honolulu",
                            Country = "United States",
                            Date = new DateTime(2012, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "My stay was decent, this place could use some more spiders. I am going to steal the Declaration of Independence.",
                            Destination = "Alley behind Quiznos",
                            Rating = 6,
                            UserName = "Nic_Cage"
                        },
                        new
                        {
                            ReviewId = 6,
                            Address = "456 Coral Ave",
                            City = "Cairns",
                            Country = "Australia",
                            Date = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A diver's paradise with stunning coral reefs and diverse marine life.",
                            Destination = "Great Barrier Reef",
                            Rating = 10,
                            UserName = "OceanExplorer"
                        },
                        new
                        {
                            ReviewId = 7,
                            Address = "789 Inca Trail",
                            City = "Cusco",
                            Country = "Peru",
                            Date = new DateTime(2021, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mystical ancient city hidden in the mountains. The hike was challenging but rewarding!",
                            Destination = "Machu Picchu",
                            Rating = 9,
                            UserName = "HistoryBuff2021"
                        },
                        new
                        {
                            ReviewId = 8,
                            Address = "101 Sunset Ave",
                            City = "Thera",
                            Country = "Greece",
                            Date = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Breathtaking views, delicious food, and stunning sunsets. A romantic getaway!",
                            Destination = "Santorini",
                            Rating = 9,
                            UserName = "IslandDreamer"
                        },
                        new
                        {
                            ReviewId = 9,
                            Address = "555 Canyon Road",
                            City = "Arizona",
                            Country = "United States",
                            Date = new DateTime(2020, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An awe-inspiring natural wonder. The views from the rim are incredible!",
                            Destination = "Grand Canyon",
                            Rating = 9,
                            UserName = "NatureLover123"
                        },
                        new
                        {
                            ReviewId = 10,
                            Address = "222 Magic Way",
                            City = "Tokyo",
                            Country = "Japan",
                            Date = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Magical experience with exciting rides and delightful characters. A must-visit for Disney lovers!",
                            Destination = "Tokyo Disneyland",
                            Rating = 8,
                            UserName = "DisneyFanatic"
                        },
                        new
                        {
                            ReviewId = 11,
                            Address = "321 Canal Street",
                            City = "Amsterdam",
                            Country = "Netherlands",
                            Date = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beautiful canals lined with picturesque houses. Renting a boat was a fantastic way to explore the city!",
                            Destination = "Amsterdam Canals",
                            Rating = 9,
                            UserName = "CultureExplorer"
                        },
                        new
                        {
                            ReviewId = 12,
                            Address = "777 Pyramid Road",
                            City = "Giza",
                            Country = "Egypt",
                            Date = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Marvelous ancient structures with a rich history. The Sphinx is impressive!",
                            Destination = "Pyramids of Giza",
                            Rating = 9,
                            UserName = "AncientHistoryFan"
                        },
                        new
                        {
                            ReviewId = 13,
                            Address = "444 Waterfall Ave",
                            City = "Puerto Iguazu",
                            Country = "Argentina",
                            Date = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Absolutely stunning waterfalls surrounded by lush rainforest. A natural wonder!",
                            Destination = "Iguazu Falls",
                            Rating = 10,
                            UserName = "NatureEnthusiast"
                        },
                        new
                        {
                            ReviewId = 14,
                            Address = "999 Marina Walk",
                            City = "Dubai",
                            Country = "United Arab Emirates",
                            Date = new DateTime(2022, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A vibrant waterfront area with impressive skyscrapers and luxurious yachts.",
                            Destination = "Dubai Marina",
                            Rating = 8,
                            UserName = "LuxuryTraveler"
                        },
                        new
                        {
                            ReviewId = 15,
                            Address = "789 Inca Trail",
                            City = "Cusco",
                            Country = "Peru",
                            Date = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A once-in-a-lifetime experience. The ancient ruins are awe-inspiring!",
                            Destination = "Machu Picchu",
                            Rating = 9,
                            UserName = "Adventurer123"
                        },
                        new
                        {
                            ReviewId = 16,
                            Address = "333 Wall Street",
                            City = "Beijing",
                            Country = "China",
                            Date = new DateTime(2021, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An incredible feat of engineering with breathtaking views. Be prepared for a long walk!",
                            Destination = "Great Wall of China",
                            Rating = 9,
                            UserName = "HistoryExplorer"
                        },
                        new
                        {
                            ReviewId = 17,
                            Address = "888 Taj Road",
                            City = "Agra",
                            Country = "India",
                            Date = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A magnificent mausoleum with stunning architecture. The marble work is exquisite!",
                            Destination = "Taj Mahal",
                            Rating = 10,
                            UserName = "ArchitecturalWonders"
                        },
                        new
                        {
                            ReviewId = 18,
                            Address = "777 Safari Drive",
                            City = "Arusha",
                            Country = "Tanzania",
                            Date = new DateTime(2023, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A wildlife enthusiast's dream. Witnessing the Great Migration was an unforgettable experience!",
                            Destination = "Serengeti National Park",
                            Rating = 10,
                            UserName = "WildlifeExplorer"
                        },
                        new
                        {
                            ReviewId = 19,
                            Address = "789 Inca Trail",
                            City = "Cusco",
                            Country = "Peru",
                            Date = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A challenging hike to reach the ancient ruins, but the view from the Sun Gate was worth it!",
                            Destination = "Machu Picchu",
                            Rating = 9,
                            UserName = "MountainHiker"
                        },
                        new
                        {
                            ReviewId = 20,
                            Address = "555 Canal Grande",
                            City = "Venice",
                            Country = "Italy",
                            Date = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Navigating the canals on a gondola was a romantic and enchanting experience.",
                            Destination = "Venice",
                            Rating = 9,
                            UserName = "RomanticTraveler"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
