// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    partial class TravelApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Address = "123 Beach st",
                            City = "Honolulu",
                            Country = "United States",
                            Date = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lovely vacation destination with great weather. No spiders at all!",
                            Destination = "Waikiki Beach",
                            Rating = 9,
                            UserName = "Mr_ReviewGuy"
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "San Diego",
                            Country = "United States",
                            Date = new DateTime(2006, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sunny San Diego offers a perfect blend of beach bliss and urban spiders",
                            Destination = "Coronado",
                            Rating = 7,
                            UserName = "Marcus"
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Chicago",
                            Country = "United States",
                            Date = new DateTime(2011, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tons of spiders, I loved it",
                            Destination = "Lou Malnati's Pizzaria",
                            Rating = 10,
                            UserName = "Jumping_Spider"
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Tokyo",
                            Country = "Japan",
                            Date = new DateTime(2009, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basically the future, they have robot spiders",
                            Destination = "マクドナルド",
                            Rating = 8,
                            UserName = "Marcus"
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Honolulu",
                            Country = "United States",
                            Date = new DateTime(2012, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "My stay was decent, this place could use some more spiders. I am going to steal the Declaration of Independence.",
                            Destination = "Alley behind Quiznos",
                            Rating = 6,
                            UserName = "Nic_Cage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
